include: package:flutter_lints/flutter.yaml

# Rules

linter:
  rules:
    - always_specify_types
    - always_declare_return_types
    - prefer_single_quotes
    - always_use_package_imports
    - avoid_empty_else
    - avoid_redundant_argument_values